### ISSUE TITLE
Hi, may I suggest a readme.md file?

### ISSUE THREAD

**Issue by xrviv** [BEEBSDONE/MeShell_Nodejs#1]
We're cataloging nostr projects and would appreciate it if more information is available about yours. Thank you!

**Comment by BEEBSDONE** [comment]
hello, I added README file if you want to read. 
Thank you!

**Comment by xrviv** [comment]
This is awesome!

**Comment by BEEBSDONE** [comment]
Thank you! We can compare MeShell to substack or medium of Nostr.

**Comment by xrviv** [comment]
That is really cool!

![image](https://user-images.githubusercontent.com/44260360/226083518-6a43cd02-599d-470e-bd1f-bd01af545db1.png)

**Comment by xrviv** [comment]
Wanna share your nPub?
